version: '3.8'

services:
  scala-app:
    build:
      context: .
      dockerfile: scala/Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"