name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run tests
      run: sbt test

    - name: Build Scala project
      run: sbt assembly

    - name: Build Docker image
      run: docker build -t volunteer-aid-image .
        
    - name: Save Docker image as tar
      run: |
        docker save -o volunteer-aid-image.tar volunteer-aid-image

    - name: Use SSH key to access server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
        
    - name: Copy Docker image to server
      run: |
        scp volunteer-aid-image.tar "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USERNAME }}/"

    - name: Load Docker image
      run: |
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo docker load -i volunteer-aid-image.tar'

    - name: Stop Docker container if running
      run: |
        if ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo docker ps -a --filter "name=volunteer-aid" --format '{{.Names}}'' | grep -q "volunteer-aid"; then
          echo "Stopping the volunteer-aid container..."
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo docker stop volunteer-aid'
        else
          echo "The volunteer-aid container is not running."
        fi
    - name: Start Docker container
      run: |
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo docker run -p 8080:8080 --name volunteer-aid -d --rm volunteer-aid-image'